<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- 12.5.0 is the latest version under Apache 2.0 license (v13+ is commercial) -->
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
  </ItemGroup>

</Project>
